apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-cert-ingress
spec:
  tls:
  -  secretName: redis-cert
  rules:
  - host: pki-redis.com
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: hello-service
              port:
                number: 80
